### ISSUE TITLE
1.16.5 advanced peripherals

### ISSUE THREAD

**Issue by makjak** [merlinlikethewizard/Mastermine#18]
hi  I tried advanced peripherals but i can not make it work with chunky turtles.
mastermine recon as mining turtles.

I am using 0.5b (the release version).
I also tried the alpha version.
Is something that i can do so I will make the chunky turtles to work?

*Edit
I used the pastebin code now i copied all the folder and all are ok

**Comment by merlinlikethewizard** [comment]
Glad you got it to work! This is why I need a releases section.
