### ISSUE TITLE
Failed to open file /mine/153, -57/11/405

### ISSUE THREAD

**Issue by PanGeo-Code** [merlinlikethewizard/Mastermine#19]
I have been using this script with 16 turtles 8 miners and 8 chunky turtles and at minimum 5 days non stop mining.

But yesterday i ran into this problem, and i fixed it by removing all of the turtle files. but today the system broke in the same way.

Steps to reproduce: 

Setup system with 8 mining turtles 8 chunky turtles, leave them on for a few days, and hope it breaks 

Pressing reboot on the main controll screen or reboot might of have created the issue.
or update. 

Turtles all display Nil.

if you cant reproduce it i could give you my server ip so you can check it out?

![Error](https://user-images.githubusercontent.com/81773780/119693255-65d23900-be4c-11eb-8dd3-9f3ea6fe8db7.PNG)

**Comment by PanGeo-Code** [comment]
My Discord: PanGeo_#5337

**Comment by merlinlikethewizard** [comment]
Fixed! Hub was opening mine files for reading but not closing them, and it hit a maximum limit.
