### ISSUE TITLE
Chunkloader Turtles lose connection every few seconds

### ISSUE THREAD

**Issue by Terandox** [merlinlikethewizard/Mastermine#21]
I play on minecraft 1.16.5 and use the chunky turtles from advanced peripherals.
After i installed every thing , all was working normaly.
After 1 hour or so the chunky turtles started to lose connection every few seconds... but the mining turtles dont.

Please help

-------------------------------------------------------------------------------------------------------------------------------------------------------
I found the problem.
I had to much chunky turtles in my world
After i removes the chunky turtles in my tree and my cropfarm, it worked normaly again

**Comment by Eforen** [comment]
You should not edit your original post with the solution you should post a new comment with the solution and mark the issue closed. Please do so @Terandox

**Comment by merlinlikethewizard** [comment]
Interesting, didn't know there was a chunk loader limit. In any case, glad you figured it out
