### ISSUE TITLE
Break

### ISSUE THREAD

**Issue by rayjay7225** [merlinlikethewizard/Mastermine#24]
I would like to make a proposition to add a break feature like in the screenshot
![image](https://user-images.githubusercontent.com/79537106/123984626-1344e900-d9c5-11eb-986c-a1aafebabe54.png)
because i tried to implement it myself but i'm dumb ald don't know a lot, the button would make the bot break the block in front of it.

**Comment by merlinlikethewizard** [comment]
Done!
