### ISSUE TITLE
Some Ores not mined

### ISSUE THREAD

**Issue by http403** [merlinlikethewizard/Mastermine#26]
I have discovered that the turtles doesn't mine some ores including vanilla Minecraft ores like iron. I think this should be a bug. Thank you.

**Comment by PanGeo-Code** [comment]
you can add them yourself with:

edit disk/hib_files/config.lua

Scroll down a bit and you should find it

**Comment by PanGeo-Code** [comment]
> I have discovered that the turtles doesn't mine some ores including vanilla Minecraft ores like iron. I think this should be a bug. Thank you.

![Turtle ores](https://user-images.githubusercontent.com/81773780/125318390-167f9380-e33a-11eb-85be-e0172f1fc268.PNG)

I hope this is a good explanaition to why it skips some ores.

**Comment by http403** [comment]
I see. That's why I saw those unmined block are all above the track. Thanks for explaining.
