### ISSUE TITLE
Center issue

### ISSUE THREAD

**Issue by BalintXHD** [merlinlikethewizard/Mastermine#40]
The gps is working, the turtles are in the correct position, but the hub reports that the center is an entirely different coordinate. And of course the turtles are not working

**Comment by merlinlikethewizard** [comment]
Have you set the mine_center in `disk/hub_files/config.lua`, and then updated the hub with `update`?

**Comment by BalintXHD** [comment]
No, but i fixed it by manually writing in the other config file.
