### ISSUE TITLE
Infinite tunnel when obstructed by block while turtle joining the queue

### ISSUE THREAD

**Issue by XxInvictus** [merlinlikethewizard/Mastermine#7]
I have found out that if the turtle encounters a block while trying to get to the end of the staging area queue it will mine the block obstructing, but then continuously try to tunnel in a straight line. I believe I had to reboot and reset the affected turtle in order to get it to return home.

**Comment by merlinlikethewizard** [comment]
Huh, I'll take a look at that. It was fine after a reboot?

**Comment by Makergear25** [comment]
I'm not sure if I am having the same problem or no but when I am adding a turtle I face it towards the disk drive run the code and link it but once I add the one piece of coal and refuel it will move turn to the left and tunnel for ever.

**Comment by ramonGonzEdu** [comment]
> I'm not sure if I am having the same problem or no but when I am adding a turtle I face it towards the disk drive run the code and link it but once I add the one piece of coal and refuel it will move turn to the left and tunnel for ever.

Are you sure that you changed where the base is?

**Comment by Makergear25** [comment]
> > I'm not sure if I am having the same problem or no, but when I am adding a turtle, I face it towards the disk drive, run the code and link it, but once I add the one piece of coal and refuel it will move turn to the left and tunnel forever.
> 
> Are you sure that you changed where the base is?

I'm not sure what you mean.

**Comment by Makergear25** [comment]
@ramonGonzEdu Yes I did change it Can you think of anything else.

Thank you

**Comment by RGFTheCoder** [comment]
Did you possibly mess up when you made the gps system, giving incorrect coordinates?
