### ISSUE TITLE
Turtles not moving once activated

### ISSUE THREAD

**Issue by realares0414** [merlinlikethewizard/Mastermine#8]
when I place the turtles down and run the turtle command it only half works, the turtles turn, move to calibrate and then return to where they were, going idle immediately after.

here's a clip of what happened and me following your suggestions for some other issues:
https://drive.google.com/file/d/1805ktr8bfg8NM_RNYkg0mYn6EbhYvyOB/view?usp=sharing

**Comment by merlinlikethewizard** [comment]
I see you closed the issue, did you solve the problem? I'm watching what you uploaded and I have to say I'm still working on figuring out what could be going wrong.

**Comment by realares0414** [comment]
Yes, I did find out how to fix the issue, I just had to break and replace
the turtle and it worked perfectly.
