### ISSUE TITLE
Failed to load API

### ISSUE THREAD

**Issue by JTGK19** [merlinlikethewizard/Mastermine#9]
I've recently downloaded and tried to use the code but when I try to start up the system using disk/hub.lua I get this error startup.lua:12: Failed to load API config due to config:105: ')' expected. I'm not sure what is causing this and I would appreciate a hand with this.

**Comment by merlinlikethewizard** [comment]
Sounds like there's an issue in the config file in the mine levels. I'm assuming you edited the mine levels? Any chance a `{` was replaced with a `(`?

**Comment by JTGK19** [comment]
That's what was causing the problem. Thanks for the help, I cant believe it was something so simple.

**Comment by merlinlikethewizard** [comment]
Glad to hear it! Lemme know if you have any other problems
